/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "#082936",
        deep: "#052f3f",
        ocean: "#087f8c",
        sea: "#23a6a6",
        signature: "#8fddd5",
        foam: "#e8f5f2",
        sand: "#f7f4ee",
        gold: "#e6a73c",
        coral: "#e8755b",
        line: "#dbe5e5",
        muted: "#60737a",
        aqua: "#8fddd5",
        ok: "#177469",
        "ok-soft": "#eafaf5",
        "ok-line": "#a9e0d0",
        warn: "#8a5a06",
        "warn-soft": "#fff7e6",
        "warn-line": "#f0d59a",
        danger: "#b0301c",
        "danger-soft": "#fdeeea",
        "danger-line": "#f6c9be",
        info: "#145c72",
        "info-soft": "#e8f1fb",
        "info-line": "#bcd9ea",
      },
      fontFamily: {
        sans: ["DM Sans", "system-ui", "sans-serif"],
        display: ["Manrope", "DM Sans", "sans-serif"],
      },
      borderRadius: { card: "18px" },
      boxShadow: { naboat: "0 24px 70px rgba(5,47,63,.14)" },
    },
  },
  plugins: [],
};
